name: searchontology
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.9
  - inflect=3.0.2
  - nltk=3.4.5
  - numpy=1.17.3
  - numpy-base=1.17.3
  - pandas=0.25.3
  - rdflib=4.2.2
  - requests=2.22.0
  - sparqlwrapper=1.8.2
  - urllib3=1.24.2
